services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./express
    ports:
      - "3000:3000"
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=12345
      - PGDATABASE=Task-Management
      - PGPORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
